-- Snapshot of the apps_by_matthew schema, exported from the database client.
-- Tracked so schema drift shows up in diffs. This is a REFERENCE SNAPSHOT, not a
-- migration or a bootstrap script — do not run it to rebuild the database:
--
--   1. The four CREATE SEQUENCE blocks below are the sequences already owned by the
--      IDENTITY columns; the exporter emits them separately. Replaying this file would
--      create a second, unowned set.
--   2. dim_application_embedding.embedding exports as `public.vector`, losing pgvector's
--      typmod. The live column is `vector(1536)` and must stay that way — a rebuild from
--      this file would leave it unpinned, which `npm run check-db` flags as a warning.
--
-- Re-export after any schema change, and run `npm run check-db` to confirm the live
-- database still matches what the code expects.

-- DROP SCHEMA apps_by_matthew;

CREATE SCHEMA apps_by_matthew AUTHORIZATION postgres;

-- DROP SEQUENCE apps_by_matthew.dim_application_application_key_seq;

CREATE SEQUENCE apps_by_matthew.dim_application_application_key_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE apps_by_matthew.dim_application_application_key_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE apps_by_matthew.dim_application_application_key_seq TO postgres;

-- DROP SEQUENCE apps_by_matthew.dim_skill_skill_key_seq;

CREATE SEQUENCE apps_by_matthew.dim_skill_skill_key_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE apps_by_matthew.dim_skill_skill_key_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE apps_by_matthew.dim_skill_skill_key_seq TO postgres;

-- DROP SEQUENCE apps_by_matthew.dim_skill_type_skill_type_key_seq;

CREATE SEQUENCE apps_by_matthew.dim_skill_type_skill_type_key_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE apps_by_matthew.dim_skill_type_skill_type_key_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE apps_by_matthew.dim_skill_type_skill_type_key_seq TO postgres;

-- DROP SEQUENCE apps_by_matthew.dim_support_status_support_status_key_seq;

CREATE SEQUENCE apps_by_matthew.dim_support_status_support_status_key_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE apps_by_matthew.dim_support_status_support_status_key_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE apps_by_matthew.dim_support_status_support_status_key_seq TO postgres;
-- apps_by_matthew.dim_skill_type definition

-- Drop table

-- DROP TABLE apps_by_matthew.dim_skill_type;

CREATE TABLE apps_by_matthew.dim_skill_type (
	skill_type_key int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	skill_type text NOT NULL,
	created_at timestamptz NULL,
	updated_at timestamptz NULL,
	deleted_at timestamptz NULL,
	CONSTRAINT dim_skill_type_pkey PRIMARY KEY (skill_type_key)
);

-- Permissions

ALTER TABLE apps_by_matthew.dim_skill_type OWNER TO postgres;
GRANT ALL ON TABLE apps_by_matthew.dim_skill_type TO postgres;


-- apps_by_matthew.dim_support_status definition

-- Drop table

-- DROP TABLE apps_by_matthew.dim_support_status;

CREATE TABLE apps_by_matthew.dim_support_status (
	support_status_key int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	support_status text NOT NULL,
	deleted_at timestamptz NULL,
	created_at timestamptz DEFAULT now() NULL,
	updated_at timestamptz NULL,
	CONSTRAINT dim_support_status_pkey PRIMARY KEY (support_status_key)
);

-- Permissions

ALTER TABLE apps_by_matthew.dim_support_status OWNER TO postgres;
GRANT ALL ON TABLE apps_by_matthew.dim_support_status TO postgres;


-- apps_by_matthew.dim_application definition

-- Drop table

-- DROP TABLE apps_by_matthew.dim_application;

CREATE TABLE apps_by_matthew.dim_application (
	application_key int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	title text NOT NULL,
	description text NULL,
	publish_date date NOT NULL,
	support_status_key int4 NOT NULL,
	image_filename text NULL,
	deployed_url text NULL,
	is_featured bool DEFAULT false NOT NULL,
	deleted_at timestamptz NULL,
	updated_at timestamptz NULL,
	created_at timestamptz DEFAULT now() NULL,
	CONSTRAINT dim_application_pkey PRIMARY KEY (application_key),
	CONSTRAINT dim_application_title_key UNIQUE (title),
	CONSTRAINT dim_application_support_status_key_fkey FOREIGN KEY (support_status_key) REFERENCES apps_by_matthew.dim_support_status(support_status_key)
);
CREATE INDEX dim_application_support_status_key_idx ON apps_by_matthew.dim_application USING btree (support_status_key);

-- Permissions

ALTER TABLE apps_by_matthew.dim_application OWNER TO postgres;
GRANT ALL ON TABLE apps_by_matthew.dim_application TO postgres;


-- apps_by_matthew.dim_application_embedding definition

-- Drop table

-- DROP TABLE apps_by_matthew.dim_application_embedding;

CREATE TABLE apps_by_matthew.dim_application_embedding (
	application_key int4 NOT NULL,
	model_version text NOT NULL,
	embedding public.vector NOT NULL,
	created_at timestamptz DEFAULT now() NULL,
	CONSTRAINT dim_application_embedding_pkey PRIMARY KEY (application_key, model_version),
	CONSTRAINT dim_application_embedding_application_key_fkey FOREIGN KEY (application_key) REFERENCES apps_by_matthew.dim_application(application_key)
);

-- Permissions

ALTER TABLE apps_by_matthew.dim_application_embedding OWNER TO postgres;
GRANT ALL ON TABLE apps_by_matthew.dim_application_embedding TO postgres;


-- apps_by_matthew.dim_skill definition

-- Drop table

-- DROP TABLE apps_by_matthew.dim_skill;

CREATE TABLE apps_by_matthew.dim_skill (
	skill_key int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	skill text NOT NULL,
	skill_type_key int4 NOT NULL,
	is_proficient bool NOT NULL,
	is_visible_in_app_details bool NOT NULL,
	is_hidden bool DEFAULT false NOT NULL,
	provide_disclaimer bool DEFAULT false NOT NULL,
	deleted_at timestamptz NULL,
	created_at timestamptz NULL,
	updated_at timestamptz NULL,
	CONSTRAINT dim_skill_pkey PRIMARY KEY (skill_key),
	CONSTRAINT dim_skill_skill_type_key_fkey FOREIGN KEY (skill_type_key) REFERENCES apps_by_matthew.dim_skill_type(skill_type_key)
);
CREATE INDEX dim_skill_skill_type_key_idx ON apps_by_matthew.dim_skill USING btree (skill_type_key);

-- Permissions

ALTER TABLE apps_by_matthew.dim_skill OWNER TO postgres;
GRANT ALL ON TABLE apps_by_matthew.dim_skill TO postgres;


-- apps_by_matthew.bridge_application_repository definition

-- Drop table

-- DROP TABLE apps_by_matthew.bridge_application_repository;

CREATE TABLE apps_by_matthew.bridge_application_repository (
	application_key int4 NOT NULL,
	repository_url text NOT NULL,
	CONSTRAINT bridge_application_repository_pkey PRIMARY KEY (application_key, repository_url),
	CONSTRAINT bridge_application_repository_application_key_fkey FOREIGN KEY (application_key) REFERENCES apps_by_matthew.dim_application(application_key)
);

-- Permissions

ALTER TABLE apps_by_matthew.bridge_application_repository OWNER TO postgres;
GRANT ALL ON TABLE apps_by_matthew.bridge_application_repository TO postgres;


-- apps_by_matthew.bridge_application_skill definition

-- Drop table

-- DROP TABLE apps_by_matthew.bridge_application_skill;

CREATE TABLE apps_by_matthew.bridge_application_skill (
	application_key int4 NOT NULL,
	skill_key int4 NOT NULL,
	CONSTRAINT bridge_application_skill_pkey PRIMARY KEY (application_key, skill_key),
	CONSTRAINT bridge_application_skill_application_key_fkey FOREIGN KEY (application_key) REFERENCES apps_by_matthew.dim_application(application_key),
	CONSTRAINT bridge_application_skill_skill_key_fkey FOREIGN KEY (skill_key) REFERENCES apps_by_matthew.dim_skill(skill_key)
);
CREATE INDEX bridge_application_skill_skill_key_idx ON apps_by_matthew.bridge_application_skill USING btree (skill_key);

-- Permissions

ALTER TABLE apps_by_matthew.bridge_application_skill OWNER TO postgres;
GRANT ALL ON TABLE apps_by_matthew.bridge_application_skill TO postgres;




-- Permissions

GRANT ALL ON SCHEMA apps_by_matthew TO postgres;