-- Chat conversation log.
--
-- Adds per-message logging to the /api/chat endpoint, which until now persisted nothing.
-- Grain is ONE ROW PER MESSAGE: a single POST /api/chat writes two rows (the user's
-- message and the assistant's reply) sharing a turn_ordinal.
--
-- Run this against the database, then re-export backend/ddl.sql and run
-- `npm run check-db`.

-- ---------------------------------------------------------------------------
-- fact_chat_message
-- ---------------------------------------------------------------------------
--
-- Column applicability by role. Per-message grain means the request-side and
-- response-side facts land on different rows; both are nullable and each is populated
-- only on the row it describes.
--
--   role = 'user'       ip_address, user_agent, embedding_model, embedding_ms, search_ms
--   role = 'assistant'  chat_model, prompt_tokens, completion_tokens, completion_ms,
--                       latency_ms, is_error, error_detail, and the retrieved sources
--                       in bridge_chat_message_application
--
-- Deviations from the dimension tables, all deliberate:
--
--   * int8 identity, not int4. This table grows per message rather than per portfolio
--     entry, so the int4 ceiling is a real limit here.
--   * No deleted_at. The dimensions soft-delete to keep foreign keys satisfied; a log
--     has no dependents except its own bridge (which cascades), and a soft-deleted log
--     row would defeat the point of a retention purge.
--   * No updated_at. Rows are immutable once written.
--   * created_at is NOT NULL DEFAULT now(), unlike dim_skill / dim_skill_type where it
--     is a plain nullable column. Rows here are inserted by more than one code path
--     over time, so the default is the guarantee rather than the data layer.

CREATE TABLE apps_by_matthew.fact_chat_message (
	chat_message_key int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,

	-- Client-supplied on every turn after the first, and never validated by the API.
	-- Treat it as a grouping hint, not an identity: anyone can post an arbitrary
	-- session_id, including one already in use. The length check keeps a hostile client
	-- from stuffing the column.
	session_id text NOT NULL,

	-- Shared by both rows of one request/response pair. Redundant with message_ordinal
	-- while roles strictly alternate, but it survives that assumption breaking (a
	-- system message, a retried turn) and makes turn-level joins unambiguous.
	turn_ordinal int4 NOT NULL,

	-- Position within the session. Assigned at insert time from the current MAX for the
	-- session; the unique constraint below is what makes that safe.
	message_ordinal int4 NOT NULL,

	role text NOT NULL,

	-- For role='user' this is the SANITIZED message — HTML stripped and truncated to
	-- 500 chars by sanitize_input() — i.e. exactly what the model was shown. The raw
	-- inbound text is not retained. Flip the call site if you need the raw string for
	-- abuse review instead.
	content text NOT NULL,

	-- Request-side facts (role='user').
	ip_address inet NULL,
	user_agent text NULL,
	embedding_model text NULL,
	embedding_ms int4 NULL,
	search_ms int4 NULL,

	-- Response-side facts (role='assistant').
	chat_model text NULL,
	prompt_tokens int4 NULL,
	completion_tokens int4 NULL,
	completion_ms int4 NULL,
	latency_ms int4 NULL,

	-- The handler's catch-all returns a canned apology to the user. Without this flag
	-- those rows are indistinguishable from a real answer.
	is_error bool DEFAULT false NOT NULL,
	error_detail text NULL,

	created_at timestamptz DEFAULT now() NOT NULL,

	CONSTRAINT fact_chat_message_pkey PRIMARY KEY (chat_message_key),
	CONSTRAINT fact_chat_message_session_id_message_ordinal_key UNIQUE (session_id, message_ordinal),
	CONSTRAINT fact_chat_message_role_check CHECK (role IN ('user', 'assistant')),
	CONSTRAINT fact_chat_message_session_id_check CHECK (length(session_id) <= 128)
);

-- Retention purges and time-range analytics both scan by date.
CREATE INDEX fact_chat_message_created_at_idx ON apps_by_matthew.fact_chat_message USING btree (created_at);

-- Failed turns are the rare case you most want to pull up; partial keeps it tiny.
CREATE INDEX fact_chat_message_is_error_idx ON apps_by_matthew.fact_chat_message USING btree (created_at) WHERE is_error;

-- Session replay is served by the (session_id, message_ordinal) unique index.

ALTER TABLE apps_by_matthew.fact_chat_message OWNER TO postgres;
GRANT ALL ON TABLE apps_by_matthew.fact_chat_message TO postgres;


-- ---------------------------------------------------------------------------
-- bridge_chat_message_application
-- ---------------------------------------------------------------------------
--
-- The applications vector search surfaced for a turn, attached to the ASSISTANT row —
-- they are the context that produced that reply, and they are what the API returns
-- alongside it as `sources`.
--
-- A bridge rather than a jsonb column, matching how the rest of the schema handles
-- many-to-many. The cost is an FK into dim_application; that is safe because
-- applications are only ever soft-deleted. The benefit is that "which projects does the
-- chatbot actually surface" is a plain GROUP BY instead of JSON extraction.

CREATE TABLE apps_by_matthew.bridge_chat_message_application (
	chat_message_key int8 NOT NULL,
	application_key int4 NOT NULL,

	-- VectorSearchHelper's `score`, i.e. 1 - cosine distance, roughly 0-1.
	similarity_score float4 NOT NULL,

	CONSTRAINT bridge_chat_message_application_pkey PRIMARY KEY (chat_message_key, application_key),
	CONSTRAINT bridge_chat_message_application_chat_message_key_fkey FOREIGN KEY (chat_message_key)
		REFERENCES apps_by_matthew.fact_chat_message(chat_message_key) ON DELETE CASCADE,
	CONSTRAINT bridge_chat_message_application_application_key_fkey FOREIGN KEY (application_key)
		REFERENCES apps_by_matthew.dim_application(application_key)
);

CREATE INDEX bridge_chat_message_application_application_key_idx ON apps_by_matthew.bridge_chat_message_application USING btree (application_key);

ALTER TABLE apps_by_matthew.bridge_chat_message_application OWNER TO postgres;
GRANT ALL ON TABLE apps_by_matthew.bridge_chat_message_application TO postgres;


-- ---------------------------------------------------------------------------
-- Retention
-- ---------------------------------------------------------------------------
--
-- ip_address and user_agent are personal data collected on a public, unauthenticated
-- endpoint, so this table should not accumulate indefinitely. There is no scheduled job
-- yet; the purge is a single statement, and the bridge cascades:
--
--   DELETE FROM apps_by_matthew.fact_chat_message
--   WHERE created_at < now() - interval '90 days';
--
-- To keep the conversation text for analytics but drop the identifiers sooner:
--
--   UPDATE apps_by_matthew.fact_chat_message
--   SET ip_address = NULL, user_agent = NULL
--   WHERE created_at < now() - interval '30 days'
--     AND (ip_address IS NOT NULL OR user_agent IS NOT NULL);
