# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Push to S3

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/**'

env:
  AWS_REGION: us-east-1
  AWS_S3_BUCKET: www.appsbymatthew.com

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build
      - name: Upload to S3
        run: aws s3 sync ./dist/. s3://${{ env.AWS_S3_BUCKET }}